### ISSUE TITLE
Anonimato 

### ISSUE THREAD

**Issue by BeastOfShadow** [GorlaA/Votazioni#10]
Da risolvere la questione sull'anonimato dei non votanti per quanto riguarda le votazioni anonime.

**ESEMPIO**
Se ci sono solo due persone nel gruppo e vota solo una persona, saprò per certo chi sarà il votante (e di conseguenza, chi non lo è).
![daCapire](https://user-images.githubusercontent.com/57445571/193416057-2045ab3b-5e7d-4e90-aabb-6b3bb5572df9.PNG)

**Comment by Toneskater** [comment]
It's a feature!!!!
